image: debian:latest

variables:
  DEBIAN_FRONTEND: noninteractive
  PACKAGES_FOLDER_NAME: $CI_PROJECT_DIR/packages
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - apt-get update -qq
  - apt-get install -qq -y dpkg dpkg-dev make rpm tar > /dev/null 2>&1

stages:
  - build_packages

packaging-debian:
  stage: build_packages
  script: |
    make package-deb
    mkdir $PACKAGES_FOLDER_NAME
    mv *.deb $PACKAGES_FOLDER_NAME/
  artifacts:
    name: tk-eluk-wmi-${CI_COMMIT_REF_SLUG}
    when: on_success
    paths:
      - $PACKAGES_FOLDER_NAME/*

packaging-fedora:
  stage: build_packages
  script: |
    make package-rpm
    mkdir $PACKAGES_FOLDER_NAME
    mv *.rpm $PACKAGES_FOLDER_NAME/
  artifacts:
    name: tk-eluk-wmi-${CI_COMMIT_REF_SLUG}
    when: on_success
    paths:
      - $PACKAGES_FOLDER_NAME/*
